<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>textile</string>
	</array>
	<key>firstLineMatch</key>
	<string>---</string>
	<key>name</key>
	<string>Jekyll</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{% comment %}</string>
			<key>end</key>
			<string>{% endcomment %}</string>
			<key>name</key>
			<string>comment.block.liquid</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>markup.other.output.liquid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#standard_filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#liquid_syntax</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>end</key>
			<string>%}</string>
			<key>name</key>
			<string>markup.other.tag.liquid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#standard_tags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#liquid_syntax</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>---</string>
			<key>end</key>
			<string>---</string>
			<key>name</key>
			<string>meta.config.jekyll</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>liquid_syntax</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.liquid</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.liquid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.liquid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(empty|null|true|false|forloop)\b</string>
					<key>name</key>
					<string>constant.language.liquid</string>
				</dict>
			</array>
		</dict>
		<key>standard_filters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(date|capitalize|downcase|upcase|first|last|join|sort|map|size|escape|escape_once|strip_html|strip_newlines|newline_to_br|replace|replace_first|remove|remove_first|truncate|truncatewords|prepend|append|minus|plus|times|divided_by|split|modulo|date_to_xmlschema|date_to_string|date_to_long_string|xml_escape|cgi_escape|number_of_words|array_to_sentence_string|textilize|markdownify)\b</string>
					<key>name</key>
					<string>keyword.control.filter.jekyll</string>
				</dict>
			</array>
		</dict>
		<key>standard_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(for|endfor|if|else|elsif|endif|cycle|unless|endunless|assign|capture|endcapture|include|tablerow|endtablerow|case|when|endcase|raw|endraw)\b</string>
					<key>name</key>
					<string>keyword.control.tag-name.jekyll</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not|contains|in|limit|offset|reversed)\b</string>
					<key>name</key>
					<string>keyword.operator.liquid</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.jekyll</string>
	<key>uuid</key>
	<string>3fd8426a-5a97-4d4b-abd8-782d9d5d4409</string>
</dict>
</plist>
